/*
 * EstudioFotografico 1.0 - Gerenciador de Estudio Fotografico
 * Copyright (C) 2014 Rogério Eduardo Pereira
 * 
 * This file is part of EstudioFotografico 1.0.
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU 
 * General Public License as published by the Free Software Foundation, either version 3 of the 
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package estudiofotografico.view.janelas;

import estudiofotografico.control.ControladorMalaDireta;
import estudiofotografico.view.erros.SucessoCopiarClipboard;
import java.awt.Component;
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author Rogério Eduardo Pereira
 * Data Criação: Mar 6, 2014
 */
public class MalaDireta extends javax.swing.JFrame implements KeyListener, ContainerListener{

    /**
     * Creates new form cadastroMarcas
     */
    public MalaDireta() {
        initComponents();
        addKeyAndContainerListenerRecursively(this);
        this.setLocationRelativeTo(null);        
    }
    
    //BOTAO ESC E ENTER
    //LISTENERS DO FRAME
    //KEYLISTENER RECURSIVO (COLOCA EM TODOS OS COMPONENTES)
    private void addKeyAndContainerListenerRecursively(Component c) 
    {  
        try 
        {  
            c.addKeyListener(this);  
            if (c instanceof Container) 
            {  
                Container cont = (Container) c;  
                cont.addContainerListener(this);  
                Component[] children = cont.getComponents();  
                for (int i = 0; i < children.length; i++) 
                {  
                    addKeyAndContainerListenerRecursively(children[i]);  
                }  
            }  
        } catch (Exception e) {  
            //Anuncie Aqui  
        }  
    }  
    
    //EVENTOS KEYLISTENER
    public void keyTyped(KeyEvent e) {}  
    public void keyReleased(KeyEvent e) {}  
    public void componentAdded(ContainerEvent e) {}  
    public void componentRemoved(ContainerEvent e) {}  
    public void keyPressed(KeyEvent e) 
    {
        //TECLA ENTER
        if(e.getKeyCode() == KeyEvent.VK_ENTER)
        {
            
        }
        
        //TECLA ESC
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            dispose();
        }
    }
	
	//Copia o conteudo para o cpliboard
	private void copiaEmails()
	{
		Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();    
		StringSelection selection = new StringSelection(this.textoEmails.getText());  
		clipboard.setContents(selection, null);  
	}
	
	//Gera Mala Direta
	private void gerarMalaDireta(Boolean fisico, Boolean juridico, Boolean fornecedor, Boolean locais)
	{
		control = new ControladorMalaDireta();
		String emails = new String();
		
		emails = this.control.getEmailsMalaDireta(fisico, juridico, fornecedor, locais);
		
		this.textoEmails.setText(emails);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        grupoPessoa = new javax.swing.ButtonGroup();
        painelPesquisa = new javax.swing.JPanel();
        checkClienteFisico = new javax.swing.JCheckBox();
        checkClienteJuridico = new javax.swing.JCheckBox();
        checkFornecedores = new javax.swing.JCheckBox();
        checkLocaisEvento = new javax.swing.JCheckBox();
        botaoGerar = new javax.swing.JButton();
        painelPesquisa1 = new javax.swing.JPanel();
        painelEmails = new javax.swing.JScrollPane();
        textoEmails = new javax.swing.JTextArea();
        botaoCopiar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agenda");
        setBounds(new java.awt.Rectangle(250, 230, 0, 0));

        painelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(95, 133, 169), null), "Listar Endereços de E-mails", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        checkClienteFisico.setText("Cliente (Pessoa Fisica)");

        checkClienteJuridico.setText("Cliente (Pessoa Juridica)");

        checkFornecedores.setText("Fornecedores");

        checkLocaisEvento.setText("Locais de Eventos");

        botaoGerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/email_go.png"))); // NOI18N
        botaoGerar.setText("Gerar Lista de E-Mail");
        botaoGerar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPesquisaLayout = new javax.swing.GroupLayout(painelPesquisa);
        painelPesquisa.setLayout(painelPesquisaLayout);
        painelPesquisaLayout.setHorizontalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPesquisaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkClienteJuridico)
                            .addComponent(checkClienteFisico))
                        .addGap(18, 18, 18)
                        .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkFornecedores)
                            .addComponent(checkLocaisEvento)))
                    .addGroup(painelPesquisaLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(botaoGerar)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        painelPesquisaLayout.setVerticalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkClienteFisico)
                    .addComponent(checkFornecedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkClienteJuridico)
                    .addComponent(checkLocaisEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoGerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelPesquisa1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(95, 133, 169), null), "E-Mails", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        textoEmails.setEditable(false);
        textoEmails.setColumns(20);
        textoEmails.setLineWrap(true);
        textoEmails.setRows(5);
        painelEmails.setViewportView(textoEmails);

        botaoCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/email_attach.png"))); // NOI18N
        botaoCopiar.setText("Copiar Lista E-Mails");
        botaoCopiar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoCopiarActionPerformed(evt);
            }
        });

        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/email_delete.png"))); // NOI18N
        botaoLimpar.setText("Limpar Pesquisa");
        botaoLimpar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botaoLimparMouseClicked(evt);
            }
        });
        botaoLimpar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPesquisa1Layout = new javax.swing.GroupLayout(painelPesquisa1);
        painelPesquisa1.setLayout(painelPesquisa1Layout);
        painelPesquisa1Layout.setHorizontalGroup(
            painelPesquisa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisa1Layout.createSequentialGroup()
                .addGroup(painelPesquisa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPesquisa1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelEmails, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                    .addGroup(painelPesquisa1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(botaoCopiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoLimpar)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelPesquisa1Layout.setVerticalGroup(
            painelPesquisa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelEmails, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPesquisa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCopiar)
                    .addComponent(botaoLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelPesquisa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPesquisa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLimparMouseClicked
        checkClienteFisico.setSelected(false);
        checkClienteJuridico.setSelected(false);
        checkFornecedores.setSelected(false);
        checkLocaisEvento.setSelected(false);
        
        textoEmails.setText("");
    }//GEN-LAST:event_botaoLimparMouseClicked

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoLimparActionPerformed
    {//GEN-HEADEREND:event_botaoLimparActionPerformed
		this.checkClienteFisico.setSelected(false);
		this.checkClienteJuridico.setSelected(false);
		this.checkFornecedores.setSelected(false);
		this.checkLocaisEvento.setSelected(false);
		
		this.textoEmails.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoCopiarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoCopiarActionPerformed
    {//GEN-HEADEREND:event_botaoCopiarActionPerformed
		this.copiaEmails();
		janelaSucessoCopiarClipboard = new SucessoCopiarClipboard(this, true);
		janelaSucessoCopiarClipboard.setVisible(true);
    }//GEN-LAST:event_botaoCopiarActionPerformed

    private void botaoGerarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoGerarActionPerformed
    {//GEN-HEADEREND:event_botaoGerarActionPerformed
		this.gerarMalaDireta(
								this.checkClienteFisico.isSelected(),
								this.checkClienteJuridico.isSelected(),
								this.checkFornecedores.isSelected(),
								this.checkLocaisEvento.isSelected()
							);
    }//GEN-LAST:event_botaoGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MalaDireta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MalaDireta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MalaDireta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MalaDireta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MalaDireta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCopiar;
    private javax.swing.JButton botaoGerar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JCheckBox checkClienteFisico;
    private javax.swing.JCheckBox checkClienteJuridico;
    private javax.swing.JCheckBox checkFornecedores;
    private javax.swing.JCheckBox checkLocaisEvento;
    private javax.swing.ButtonGroup grupoPessoa;
    private javax.swing.JScrollPane painelEmails;
    private javax.swing.JPanel painelPesquisa;
    private javax.swing.JPanel painelPesquisa1;
    private javax.swing.JTextArea textoEmails;
    // End of variables declaration//GEN-END:variables
	private SucessoCopiarClipboard	janelaSucessoCopiarClipboard;
	private ControladorMalaDireta	control;
}
