/*
 * EstudioFotografico 1.0 - Gerenciador de Estudio Fotografico
 * Copyright (C) 2014 Rogério Eduardo Pereira
 * 
 * This file is part of EstudioFotografico 1.0.
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU 
 * General Public License as published by the Free Software Foundation, either version 3 of the 
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package estudiofotografico.view.janelas;

import estudiofotografico.control.ControladorEmpresa;
import estudiofotografico.view.erros.*;
import static estudiofotografico.view.erros.ErroEmpresaNaoCadastrada.RET_OK;

import java.awt.Component;
import java.awt.Container;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import lookandfeel.LookAndFeelWindow;

/**
 *
 * @author farofa
 */
public class Principal extends javax.swing.JFrame implements KeyListener, ContainerListener{

    /**
     * Creates new form principal
     */
    public Principal() {
        initComponents();
        addKeyAndContainerListenerRecursively(this);
        this.setLocationRelativeTo(null);
		//Define o logotipo
		this.setLogotipo();
		//Verifica empresa
		this.verificaEmpresa();
		//Verifica tipo Usuario
		//this.verificaUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        painelBotoes = new javax.swing.JPanel();
        botaoClientes = new javax.swing.JButton();
        botaoProdutos = new javax.swing.JButton();
        botaoServicos = new javax.swing.JButton();
        botaoVendas = new javax.swing.JButton();
        botaoAgenda = new javax.swing.JButton();
        botaoMalaDireta = new javax.swing.JButton();
        Logoff = new javax.swing.JButton();
        painelLogotipo = new javax.swing.JPanel();
        labelLogotipo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroEquipamentos = new javax.swing.JMenu();
        itemCadastroEquipamentoMarca = new javax.swing.JMenuItem();
        itemCadastroEquipamentoTipo = new javax.swing.JMenuItem();
        separadorCadastroEquipamentos = new javax.swing.JPopupMenu.Separator();
        itemCadastroEquipamentoEquipamentos = new javax.swing.JMenuItem();
        menuCadastroProdutos = new javax.swing.JMenu();
        itemCadastroProdutosCategoria = new javax.swing.JMenuItem();
        separadorCadastroProdutos = new javax.swing.JPopupMenu.Separator();
        itemCadastroProdutosProdutos = new javax.swing.JMenuItem();
        menuCadastroServicos = new javax.swing.JMenu();
        itemCadastroServicosCategoria = new javax.swing.JMenuItem();
        separadorCadastroServicos = new javax.swing.JPopupMenu.Separator();
        itemCadastroServicosServicos = new javax.swing.JMenuItem();
        menuCadastroEventos = new javax.swing.JMenu();
        itemCadastroEventosTipos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemCadastroEventosLocais = new javax.swing.JMenuItem();
        menuCadastrosContatos = new javax.swing.JMenu();
        itemCadastroContatoClientes = new javax.swing.JMenuItem();
        itemCadastroContatoFornecedores = new javax.swing.JMenuItem();
        menuContatos = new javax.swing.JMenu();
        itemContatosAgenda = new javax.swing.JMenuItem();
        itemContatosMalaDireta = new javax.swing.JMenuItem();
        menuMovimentacao = new javax.swing.JMenu();
        ItemMovientacaoVendas = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        itemRelatoriosClientes = new javax.swing.JMenuItem();
        itemRelatoriosFornecedores = new javax.swing.JMenuItem();
        itemRelatoriosEquipamentos = new javax.swing.JMenuItem();
        itemRelatoriosVendas = new javax.swing.JMenuItem();
        menuRelatoriosContas = new javax.swing.JMenu();
        itemRelatoriosContasReceber = new javax.swing.JMenuItem();
        menuUtilitarios = new javax.swing.JMenu();
        itemUtilitariosCalculadora = new javax.swing.JMenuItem();
        itemUtilitariosRecibos = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        menuSistemaBackup = new javax.swing.JMenu();
        itemSistemaBackupCriar = new javax.swing.JMenuItem();
        itemSistemaBackupRestaurar = new javax.swing.JMenuItem();
        menuSistemaUsuario = new javax.swing.JMenu();
        itemSistemaUsuarioCadastrar = new javax.swing.JMenuItem();
        itemSistemaUsuarioSenha = new javax.swing.JMenuItem();
        menuSistemaSobre = new javax.swing.JMenu();
        itemSistemaSobreAparencia = new javax.swing.JMenuItem();
        itemSistemaSobreSobre = new javax.swing.JMenuItem();
        itemSistemaSobreLicenca = new javax.swing.JMenuItem();
        itemSistemaProprietario = new javax.swing.JMenuItem();
        itemSistemaLogoff = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estudio Fotografico");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(800, 600));

        painelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        painelBotoes.setAutoscrolls(true);

        botaoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/user_add_grande.png"))); // NOI18N
        botaoClientes.setText("Clientes");
        botaoClientes.setAlignmentX(5.0F);
        botaoClientes.setAlignmentY(5.0F);
        botaoClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoClientes.setFocusable(false);
        botaoClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoClientes.setMargin(new java.awt.Insets(0, 0, 0, 10));
        botaoClientes.setMaximumSize(new java.awt.Dimension(100, 60));
        botaoClientes.setMinimumSize(new java.awt.Dimension(100, 60));
        botaoClientes.setPreferredSize(new java.awt.Dimension(100, 60));
        botaoClientes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botaoClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoClientes.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botaoClientesMouseClicked(evt);
            }
        });

        botaoProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/photo-album-blue_grande.png"))); // NOI18N
        botaoProdutos.setText("Produtos");
        botaoProdutos.setAlignmentX(5.0F);
        botaoProdutos.setAlignmentY(5.0F);
        botaoProdutos.setAutoscrolls(true);
        botaoProdutos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoProdutos.setFocusable(false);
        botaoProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoProdutos.setMargin(new java.awt.Insets(0, 0, 0, 10));
        botaoProdutos.setMaximumSize(new java.awt.Dimension(100, 60));
        botaoProdutos.setMinimumSize(new java.awt.Dimension(100, 60));
        botaoProdutos.setPreferredSize(new java.awt.Dimension(100, 60));
        botaoProdutos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botaoProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoProdutos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botaoProdutosMouseClicked(evt);
            }
        });

        botaoServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/cake_grande.png"))); // NOI18N
        botaoServicos.setText("Serviços");
        botaoServicos.setAlignmentX(5.0F);
        botaoServicos.setAlignmentY(5.0F);
        botaoServicos.setAutoscrolls(true);
        botaoServicos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoServicos.setFocusable(false);
        botaoServicos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoServicos.setMargin(new java.awt.Insets(0, 0, 0, 10));
        botaoServicos.setMaximumSize(new java.awt.Dimension(100, 60));
        botaoServicos.setMinimumSize(new java.awt.Dimension(100, 60));
        botaoServicos.setPreferredSize(new java.awt.Dimension(100, 60));
        botaoServicos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botaoServicos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoServicos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botaoServicosMouseClicked(evt);
            }
        });

        botaoVendas.setBackground(new java.awt.Color(153, 153, 255));
        botaoVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/counter.png"))); // NOI18N
        botaoVendas.setText("Vendas");
        botaoVendas.setAlignmentX(5.0F);
        botaoVendas.setAlignmentY(5.0F);
        botaoVendas.setAutoscrolls(true);
        botaoVendas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoVendas.setFocusable(false);
        botaoVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoVendas.setMargin(new java.awt.Insets(0, 0, 0, 10));
        botaoVendas.setMaximumSize(new java.awt.Dimension(100, 60));
        botaoVendas.setMinimumSize(new java.awt.Dimension(100, 60));
        botaoVendas.setPreferredSize(new java.awt.Dimension(100, 60));
        botaoVendas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botaoVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoVendas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botaoVendasMouseClicked(evt);
            }
        });

        botaoAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/calendar-day_grande.png"))); // NOI18N
        botaoAgenda.setText("Agenda Telefonica");
        botaoAgenda.setAlignmentX(5.0F);
        botaoAgenda.setAlignmentY(5.0F);
        botaoAgenda.setAutoscrolls(true);
        botaoAgenda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoAgenda.setFocusable(false);
        botaoAgenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoAgenda.setMargin(new java.awt.Insets(0, 0, 0, 10));
        botaoAgenda.setMaximumSize(new java.awt.Dimension(100, 60));
        botaoAgenda.setMinimumSize(new java.awt.Dimension(100, 60));
        botaoAgenda.setPreferredSize(new java.awt.Dimension(100, 60));
        botaoAgenda.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botaoAgenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoAgenda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoAgendaActionPerformed(evt);
            }
        });

        botaoMalaDireta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/mail_grande.png"))); // NOI18N
        botaoMalaDireta.setText("Mala Direta");
        botaoMalaDireta.setAlignmentX(5.0F);
        botaoMalaDireta.setAlignmentY(5.0F);
        botaoMalaDireta.setAutoscrolls(true);
        botaoMalaDireta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoMalaDireta.setFocusable(false);
        botaoMalaDireta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoMalaDireta.setMargin(new java.awt.Insets(0, 0, 0, 10));
        botaoMalaDireta.setMaximumSize(new java.awt.Dimension(100, 60));
        botaoMalaDireta.setMinimumSize(new java.awt.Dimension(100, 60));
        botaoMalaDireta.setPreferredSize(new java.awt.Dimension(100, 60));
        botaoMalaDireta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botaoMalaDireta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoMalaDireta.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botaoMalaDiretaMouseClicked(evt);
            }
        });
        botaoMalaDireta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoMalaDiretaActionPerformed(evt);
            }
        });

        Logoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/cancel_grande.png"))); // NOI18N
        Logoff.setText("Logoff");
        Logoff.setAlignmentX(5.0F);
        Logoff.setAlignmentY(5.0F);
        Logoff.setAutoscrolls(true);
        Logoff.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Logoff.setFocusable(false);
        Logoff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logoff.setMargin(new java.awt.Insets(0, 0, 0, 10));
        Logoff.setMaximumSize(new java.awt.Dimension(100, 60));
        Logoff.setMinimumSize(new java.awt.Dimension(100, 60));
        Logoff.setPreferredSize(new java.awt.Dimension(100, 60));
        Logoff.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Logoff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Logoff.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                LogoffMouseClicked(evt);
            }
        });
        Logoff.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LogoffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoMalaDireta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logoff, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(botaoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoMalaDireta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Logoff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBotoesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoAgenda, botaoClientes, botaoMalaDireta, botaoProdutos, botaoServicos, botaoVendas});

        painelLogotipo.setLayout(new java.awt.BorderLayout());
        painelLogotipo.add(labelLogotipo, java.awt.BorderLayout.CENTER);

        menuCadastro.setText("Cadastro");

        menuCadastroEquipamentos.setText("Equipamentos");

        itemCadastroEquipamentoMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/text_list_bullets.png"))); // NOI18N
        itemCadastroEquipamentoMarca.setText("Marcas");
        itemCadastroEquipamentoMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemCadastroEquipamentoMarcaActionPerformed(evt);
            }
        });
        menuCadastroEquipamentos.add(itemCadastroEquipamentoMarca);

        itemCadastroEquipamentoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/text_list_bullets.png"))); // NOI18N
        itemCadastroEquipamentoTipo.setText("Tipos");
        itemCadastroEquipamentoTipo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemCadastroEquipamentoTipoActionPerformed(evt);
            }
        });
        menuCadastroEquipamentos.add(itemCadastroEquipamentoTipo);
        menuCadastroEquipamentos.add(separadorCadastroEquipamentos);

        itemCadastroEquipamentoEquipamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/camera.png"))); // NOI18N
        itemCadastroEquipamentoEquipamentos.setText("Equipamentos");
        itemCadastroEquipamentoEquipamentos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemCadastroEquipamentoEquipamentosActionPerformed(evt);
            }
        });
        menuCadastroEquipamentos.add(itemCadastroEquipamentoEquipamentos);

        menuCadastro.add(menuCadastroEquipamentos);

        menuCadastroProdutos.setText("Produtos");

        itemCadastroProdutosCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/text_list_bullets.png"))); // NOI18N
        itemCadastroProdutosCategoria.setText("Categorias");
        itemCadastroProdutosCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemCadastroProdutosCategoriaActionPerformed(evt);
            }
        });
        menuCadastroProdutos.add(itemCadastroProdutosCategoria);
        menuCadastroProdutos.add(separadorCadastroProdutos);

        itemCadastroProdutosProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/photo-album-blue.png"))); // NOI18N
        itemCadastroProdutosProdutos.setText("Produtos");
        itemCadastroProdutosProdutos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemCadastroProdutosProdutosActionPerformed(evt);
            }
        });
        menuCadastroProdutos.add(itemCadastroProdutosProdutos);

        menuCadastro.add(menuCadastroProdutos);

        menuCadastroServicos.setText("Serviços");

        itemCadastroServicosCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/text_list_bullets.png"))); // NOI18N
        itemCadastroServicosCategoria.setText("Categorias");
        itemCadastroServicosCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemCadastroServicosCategoriaActionPerformed(evt);
            }
        });
        menuCadastroServicos.add(itemCadastroServicosCategoria);
        menuCadastroServicos.add(separadorCadastroServicos);

        itemCadastroServicosServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/cake.png"))); // NOI18N
        itemCadastroServicosServicos.setText("Serviços");
        itemCadastroServicosServicos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemCadastroServicosServicosActionPerformed(evt);
            }
        });
        menuCadastroServicos.add(itemCadastroServicosServicos);

        menuCadastro.add(menuCadastroServicos);

        menuCadastroEventos.setText("Eventos");

        itemCadastroEventosTipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/text_list_bullets.png"))); // NOI18N
        itemCadastroEventosTipos.setText("Tipos de Eventos");
        itemCadastroEventosTipos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemCadastroEventosTiposActionPerformed(evt);
            }
        });
        menuCadastroEventos.add(itemCadastroEventosTipos);
        menuCadastroEventos.add(jSeparator1);

        itemCadastroEventosLocais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/map.png"))); // NOI18N
        itemCadastroEventosLocais.setText("Locais de Eventos");
        itemCadastroEventosLocais.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemCadastroEventosLocaisActionPerformed(evt);
            }
        });
        menuCadastroEventos.add(itemCadastroEventosLocais);

        menuCadastro.add(menuCadastroEventos);

        menuCadastrosContatos.setText("Contatos");

        itemCadastroContatoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/user_add.png"))); // NOI18N
        itemCadastroContatoClientes.setText("Clientes");
        itemCadastroContatoClientes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemCadastroContatoClientesActionPerformed(evt);
            }
        });
        menuCadastrosContatos.add(itemCadastroContatoClientes);

        itemCadastroContatoFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/FornecedorAdd.png"))); // NOI18N
        itemCadastroContatoFornecedores.setText("Fornecedores");
        itemCadastroContatoFornecedores.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemCadastroContatoFornecedoresActionPerformed(evt);
            }
        });
        menuCadastrosContatos.add(itemCadastroContatoFornecedores);

        menuCadastro.add(menuCadastrosContatos);

        barraMenu.add(menuCadastro);

        menuContatos.setText("Contatos");

        itemContatosAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/calendar-day.png"))); // NOI18N
        itemContatosAgenda.setText("Agenda Telefonica");
        itemContatosAgenda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemContatosAgendaActionPerformed(evt);
            }
        });
        menuContatos.add(itemContatosAgenda);

        itemContatosMalaDireta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/mail.png"))); // NOI18N
        itemContatosMalaDireta.setText("Mala Direta");
        itemContatosMalaDireta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemContatosMalaDiretaActionPerformed(evt);
            }
        });
        menuContatos.add(itemContatosMalaDireta);

        barraMenu.add(menuContatos);

        menuMovimentacao.setText("Movimentação");

        ItemMovientacaoVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/counter_pequeno.png"))); // NOI18N
        ItemMovientacaoVendas.setText("Vendas");
        ItemMovientacaoVendas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ItemMovientacaoVendasActionPerformed(evt);
            }
        });
        menuMovimentacao.add(ItemMovientacaoVendas);

        barraMenu.add(menuMovimentacao);

        menuRelatorios.setText("Relatórios");

        itemRelatoriosClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/user.png"))); // NOI18N
        itemRelatoriosClientes.setText("Clientes");
        itemRelatoriosClientes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemRelatoriosClientesActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemRelatoriosClientes);

        itemRelatoriosFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/user_orange.png"))); // NOI18N
        itemRelatoriosFornecedores.setText("Fornecedores");
        itemRelatoriosFornecedores.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemRelatoriosFornecedoresActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemRelatoriosFornecedores);

        itemRelatoriosEquipamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/camera.png"))); // NOI18N
        itemRelatoriosEquipamentos.setText("Equipamentos");
        itemRelatoriosEquipamentos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemRelatoriosEquipamentosActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemRelatoriosEquipamentos);

        itemRelatoriosVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/counter_pequeno.png"))); // NOI18N
        itemRelatoriosVendas.setText("Vendas");
        itemRelatoriosVendas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemRelatoriosVendasActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemRelatoriosVendas);

        menuRelatoriosContas.setText("Contas");

        itemRelatoriosContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/money_add.png"))); // NOI18N
        itemRelatoriosContasReceber.setText("À Receber");
        menuRelatoriosContas.add(itemRelatoriosContasReceber);

        menuRelatorios.add(menuRelatoriosContas);

        barraMenu.add(menuRelatorios);

        menuUtilitarios.setText("Utilitarios");

        itemUtilitariosCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/calculator.png"))); // NOI18N
        itemUtilitariosCalculadora.setText("Calculadora");
        itemUtilitariosCalculadora.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemUtilitariosCalculadoraActionPerformed(evt);
            }
        });
        menuUtilitarios.add(itemUtilitariosCalculadora);

        itemUtilitariosRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/receipt-sticky-note.png"))); // NOI18N
        itemUtilitariosRecibos.setText("Gerador Recibo");
        itemUtilitariosRecibos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemUtilitariosRecibosActionPerformed(evt);
            }
        });
        menuUtilitarios.add(itemUtilitariosRecibos);

        barraMenu.add(menuUtilitarios);

        menuSistema.setText("Sistema");

        menuSistemaBackup.setText("Backup");

        itemSistemaBackupCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/database_save.png"))); // NOI18N
        itemSistemaBackupCriar.setText("Fazer Backup");
        itemSistemaBackupCriar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemSistemaBackupCriarActionPerformed(evt);
            }
        });
        menuSistemaBackup.add(itemSistemaBackupCriar);

        itemSistemaBackupRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/database_refresh.png"))); // NOI18N
        itemSistemaBackupRestaurar.setText("Restaurar Backup");
        itemSistemaBackupRestaurar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemSistemaBackupRestaurarActionPerformed(evt);
            }
        });
        menuSistemaBackup.add(itemSistemaBackupRestaurar);

        menuSistema.add(menuSistemaBackup);

        menuSistemaUsuario.setText("Usuario");

        itemSistemaUsuarioCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/user-business.png"))); // NOI18N
        itemSistemaUsuarioCadastrar.setText("Cadastrar");
        itemSistemaUsuarioCadastrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemSistemaUsuarioCadastrarActionPerformed(evt);
            }
        });
        menuSistemaUsuario.add(itemSistemaUsuarioCadastrar);

        itemSistemaUsuarioSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/asterisk.png"))); // NOI18N
        itemSistemaUsuarioSenha.setText("Alterar Senha");
        itemSistemaUsuarioSenha.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemSistemaUsuarioSenhaActionPerformed(evt);
            }
        });
        menuSistemaUsuario.add(itemSistemaUsuarioSenha);

        menuSistema.add(menuSistemaUsuario);

        menuSistemaSobre.setText("Sobre");

        itemSistemaSobreAparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/palette.png"))); // NOI18N
        itemSistemaSobreAparencia.setText("Aparencia");
        itemSistemaSobreAparencia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemSistemaSobreAparenciaActionPerformed(evt);
            }
        });
        menuSistemaSobre.add(itemSistemaSobreAparencia);

        itemSistemaSobreSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/information.png"))); // NOI18N
        itemSistemaSobreSobre.setText("Sobre");
        itemSistemaSobreSobre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemSistemaSobreSobreActionPerformed(evt);
            }
        });
        menuSistemaSobre.add(itemSistemaSobreSobre);

        itemSistemaSobreLicenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/script.png"))); // NOI18N
        itemSistemaSobreLicenca.setText("Licença");
        itemSistemaSobreLicenca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemSistemaSobreLicencaActionPerformed(evt);
            }
        });
        menuSistemaSobre.add(itemSistemaSobreLicenca);

        menuSistema.add(menuSistemaSobre);

        itemSistemaProprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/camera-lens_menor.png"))); // NOI18N
        itemSistemaProprietario.setText("Dados da Empresa");
        itemSistemaProprietario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemSistemaProprietarioActionPerformed(evt);
            }
        });
        menuSistema.add(itemSistemaProprietario);

        itemSistemaLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/cancel.png"))); // NOI18N
        itemSistemaLogoff.setText("Logoff");
        itemSistemaLogoff.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                itemSistemaLogoffActionPerformed(evt);
            }
        });
        menuSistema.add(itemSistemaLogoff);

        barraMenu.add(menuSistema);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelLogotipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelLogotipo, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //BOTAO ESC E ENTER
    //LISTENERS DO FRAME
    //KEYLISTENER RECURSIVO (COLOCA EM TODOS OS COMPONENTES)
    private void addKeyAndContainerListenerRecursively(Component c) 
    {  
        try 
        {  
            c.addKeyListener(this);  
            if (c instanceof Container) 
            {  
                Container cont = (Container) c;  
                cont.addContainerListener(this);  
                Component[] children = cont.getComponents();  
                for (int i = 0; i < children.length; i++) 
                {  
                    addKeyAndContainerListenerRecursively(children[i]);  
                }  
            }  
        } catch (Exception e) {  
            //Anuncie Aqui  
        }  
    }  
    
    //EVENTOS KEYLISTENER
    public void keyTyped(KeyEvent e) {}  
    public void keyReleased(KeyEvent e) {}  
    public void componentAdded(ContainerEvent e) {}  
    public void componentRemoved(ContainerEvent e) {}  
    public void keyPressed(KeyEvent e) 
    {
        //TECLA ESC
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            LogoffMouseClicked(null);
        }
    }
	
	/*
	 * Método setLogotipo
	 * Define o Logotipo
	 */
	private void setLogotipo()
	{
		this.labelLogotipo.setHorizontalAlignment(SwingConstants.CENTER);  
		this.labelLogotipo.setIcon(new ImageIcon("img\\logotipo.png"));
	}
	
	/*
	 * Método verificaEmpresa
	 * Obtem se tem empresa cadastrada
	 */
	private void verificaEmpresa()
	{
		this.controlEmpresa = new ControladorEmpresa();
		if(!this.controlEmpresa.countEmpresa())
		{
			this.janelaEmpresaNaoCadastrada = new ErroEmpresaNaoCadastrada(this, true);
			this.janelaEmpresaNaoCadastrada.setVisible(true);
			if(this.janelaEmpresaNaoCadastrada.getReturnStatus() == RET_OK)
			{
				this.janelaDadosProprietario = new DadosEmpresa();
				this.janelaDadosProprietario.setVisible(true);
			}
		}
	}
	
	/*
	 * Método verificaUsuario
	 * Verifica o usuario e oculta opções dos menus se nao for administrador
	 */
	private void verificaUsuario()
	{
		if(!this.estudio.user.getNivel())
		{
			this.menuCadastroEquipamentos.setVisible(false);
			this.menuCadastroProdutos.setVisible(false);
			this.menuCadastroServicos.setVisible(false);
			this.menuCadastroEventos.setVisible(false);
			this.menuRelatorios.setVisible(false);
			this.botaoProdutos.setVisible(false);
			this.botaoServicos.setVisible(false);
			this.menuSistemaBackup.setVisible(false);
			this.itemSistemaUsuarioCadastrar.setVisible(false);
			this.itemSistemaProprietario.setVisible(false);
		}
	}
    
    private void botaoMalaDiretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMalaDiretaMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botaoMalaDiretaMouseClicked

    private void itemCadastroEquipamentoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroEquipamentoMarcaActionPerformed
        // TODO add your handling code here:
        janelaCadastroMarcasEquipamentos = new CadastroMarcasEquipamentos();
        janelaCadastroMarcasEquipamentos.setVisible(true);
    }//GEN-LAST:event_itemCadastroEquipamentoMarcaActionPerformed

    private void itemCadastroEquipamentoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroEquipamentoTipoActionPerformed
        // TODO add your handling code here:
        janelaCadastroTipoEquipamentos = new CadastroTipoEquipamentos();
        janelaCadastroTipoEquipamentos.setVisible(true);
    }//GEN-LAST:event_itemCadastroEquipamentoTipoActionPerformed

    private void itemCadastroEquipamentoEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroEquipamentoEquipamentosActionPerformed
        // TODO add your handling code here:
        janelaCadastroEquipamentos = new CadastroEquipamentos();
        janelaCadastroEquipamentos.setVisible(true);
    }//GEN-LAST:event_itemCadastroEquipamentoEquipamentosActionPerformed

    private void itemCadastroProdutosCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroProdutosCategoriaActionPerformed
        // TODO add your handling code here:
        janelaCadastroCategoriaProduto = new CadastroCategoriaProduto();
        janelaCadastroCategoriaProduto.setVisible(true);
    }//GEN-LAST:event_itemCadastroProdutosCategoriaActionPerformed

    private void itemCadastroProdutosProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroProdutosProdutosActionPerformed
        // TODO add your handling code here:
        janelaCadastroProdutos = new CadastroProdutos();
        janelaCadastroProdutos.setVisible(true);
    }//GEN-LAST:event_itemCadastroProdutosProdutosActionPerformed

    private void itemCadastroServicosCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroServicosCategoriaActionPerformed
        // TODO add your handling code here:
        janelaCadastroCategoriaServico = new CadastroCategoriaServico();
        janelaCadastroCategoriaServico.setVisible(true);
    }//GEN-LAST:event_itemCadastroServicosCategoriaActionPerformed

    private void itemCadastroServicosServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroServicosServicosActionPerformed
        // TODO add your handling code here:
        janelaCadastroServicos = new CadastroServicos();
        janelaCadastroServicos.setVisible(true);
    }//GEN-LAST:event_itemCadastroServicosServicosActionPerformed

    private void itemCadastroEventosTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroEventosTiposActionPerformed
        // TODO add your handling code here:
        janelaCadastroTipoEvento = new CadastroTipoEvento();
        janelaCadastroTipoEvento.setVisible(true);
    }//GEN-LAST:event_itemCadastroEventosTiposActionPerformed

    private void itemCadastroEventosLocaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroEventosLocaisActionPerformed
        // TODO add your handling code here:
        janelaCadastroLocaisEventos = new CadastroLocaisEventos();
        janelaCadastroLocaisEventos.setVisible(true);
    }//GEN-LAST:event_itemCadastroEventosLocaisActionPerformed

    private void itemCadastroContatoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroContatoClientesActionPerformed
        // TODO add your handling code here:
        janelaCadastroClientes = new CadastroClientes();
        janelaCadastroClientes.setVisible(true);
    }//GEN-LAST:event_itemCadastroContatoClientesActionPerformed

    private void itemCadastroContatoFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroContatoFornecedoresActionPerformed
        // TODO add your handling code here:
        janelaCadastroFornecedores = new CadastroFornecedores();
        janelaCadastroFornecedores.setVisible(true);
    }//GEN-LAST:event_itemCadastroContatoFornecedoresActionPerformed

    private void itemContatosAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemContatosAgendaActionPerformed
        // TODO add your handling code here:
        janelaAgenda = new Agenda();
        janelaAgenda.setVisible(true);
    }//GEN-LAST:event_itemContatosAgendaActionPerformed

    private void itemContatosMalaDiretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemContatosMalaDiretaActionPerformed
        // TODO add your handling code here:
        janelaMalaDireta = new MalaDireta();
        janelaMalaDireta.setVisible(true);
    }//GEN-LAST:event_itemContatosMalaDiretaActionPerformed

    private void ItemMovientacaoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMovientacaoVendasActionPerformed
        // TODO add your handling code here:
        janelaVendas = new Vendas();
        janelaVendas.setVisible(true);
    }//GEN-LAST:event_ItemMovientacaoVendasActionPerformed

    private void itemRelatoriosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRelatoriosClientesActionPerformed
        // TODO add your handling code here:
        janelaRelatorioClientes = new RelatorioClientes();
        janelaRelatorioClientes.setVisible(true);        
    }//GEN-LAST:event_itemRelatoriosClientesActionPerformed

    private void itemRelatoriosFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRelatoriosFornecedoresActionPerformed
        // TODO add your handling code here:
        janelaRelatorioFornecedores = new RelatorioFornecedores();
        janelaRelatorioFornecedores.setVisible(true);
    }//GEN-LAST:event_itemRelatoriosFornecedoresActionPerformed

    private void itemRelatoriosEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRelatoriosEquipamentosActionPerformed
        // TODO add your handling code here:
        janelaRelatorioEquipamento = new RelatorioEquipamento();
        janelaRelatorioEquipamento.setVisible(true);
    }//GEN-LAST:event_itemRelatoriosEquipamentosActionPerformed

    private void itemRelatoriosVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRelatoriosVendasActionPerformed
        // TODO add your handling code here:
        janelaRelatorioVendas = new RelatorioVendas();
        janelaRelatorioVendas.setVisible(true);
    }//GEN-LAST:event_itemRelatoriosVendasActionPerformed

    private void itemUtilitariosRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUtilitariosRecibosActionPerformed
        // TODO add your handling code here:
        janelaRecibos = new Recibos();
        janelaRecibos.setVisible(true);
    }//GEN-LAST:event_itemUtilitariosRecibosActionPerformed

    private void itemUtilitariosCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUtilitariosCalculadoraActionPerformed
        // TODO add your handling code here:
        try
        {
            Runtime.getRuntime().exec("calc.exe");
        }
        catch (Exception e)
        {
            janelaErroAbrirCalculadora = new ErroAbrirCalculadora(this, true);
            janelaErroAbrirCalculadora.setVisible(true);
        }
    }//GEN-LAST:event_itemUtilitariosCalculadoraActionPerformed

    private void botaoClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoClientesMouseClicked
        // TODO add your handling code here:
        janelaCadastroClientes = new CadastroClientes();
        janelaCadastroClientes.setVisible(true);
    }//GEN-LAST:event_botaoClientesMouseClicked

    private void botaoProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoProdutosMouseClicked
        // TODO add your handling code here:
        janelaCadastroProdutos = new CadastroProdutos();
        janelaCadastroProdutos.setVisible(true);
    }//GEN-LAST:event_botaoProdutosMouseClicked

    private void botaoServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoServicosMouseClicked
        // TODO add your handling code here:
        janelaCadastroServicos = new CadastroServicos();
        janelaCadastroServicos.setVisible(true);
    }//GEN-LAST:event_botaoServicosMouseClicked

    private void botaoVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVendasMouseClicked
        // TODO add your handling code here:
        janelaVendas = new Vendas();
        janelaVendas.setVisible(true);
    }//GEN-LAST:event_botaoVendasMouseClicked

    private void itemSistemaProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSistemaProprietarioActionPerformed
        // TODO add your handling code here:
        janelaDadosProprietario = new DadosEmpresa();
        janelaDadosProprietario.setVisible(true);
    }//GEN-LAST:event_itemSistemaProprietarioActionPerformed

    private void itemSistemaUsuarioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSistemaUsuarioCadastrarActionPerformed
        // TODO add your handling code here:
        janelaCadastroUsuario = new CadastroUsuario();
        janelaCadastroUsuario.setVisible(true);
    }//GEN-LAST:event_itemSistemaUsuarioCadastrarActionPerformed

    private void itemSistemaUsuarioSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSistemaUsuarioSenhaActionPerformed
        // TODO add your handling code here:
        janelaAlteraSenha = new AlteraSenha();
        janelaAlteraSenha.setVisible(true);
    }//GEN-LAST:event_itemSistemaUsuarioSenhaActionPerformed

    private void itemSistemaLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSistemaLogoffActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itemSistemaLogoffActionPerformed

    private void botaoMalaDiretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMalaDiretaActionPerformed
		janelaMalaDireta = new MalaDireta();
        janelaMalaDireta.setVisible(true);
    }//GEN-LAST:event_botaoMalaDiretaActionPerformed

private void LogoffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoffMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_LogoffMouseClicked

private void LogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoffActionPerformed
	System.exit(0);
}//GEN-LAST:event_LogoffActionPerformed

    private void itemSistemaBackupCriarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_itemSistemaBackupCriarActionPerformed
    {//GEN-HEADEREND:event_itemSistemaBackupCriarActionPerformed
		this.janelaBackup = new Backup();
		this.janelaBackup.setVisible(true);
    }//GEN-LAST:event_itemSistemaBackupCriarActionPerformed

    private void itemSistemaBackupRestaurarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_itemSistemaBackupRestaurarActionPerformed
    {//GEN-HEADEREND:event_itemSistemaBackupRestaurarActionPerformed
		this.janelaRestaurarBackup = new RestaurarBackup();
		this.janelaRestaurarBackup.setVisible(true);
    }//GEN-LAST:event_itemSistemaBackupRestaurarActionPerformed

    private void botaoAgendaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoAgendaActionPerformed
    {//GEN-HEADEREND:event_botaoAgendaActionPerformed
        // TODO add your handling code here:
		janelaAgenda = new Agenda();
        janelaAgenda.setVisible(true);
    }//GEN-LAST:event_botaoAgendaActionPerformed

    private void itemSistemaSobreLicencaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_itemSistemaSobreLicencaActionPerformed
    {//GEN-HEADEREND:event_itemSistemaSobreLicencaActionPerformed
		janelaLicensa = new Licenca();
		janelaLicensa.setVisible(true);
    }//GEN-LAST:event_itemSistemaSobreLicencaActionPerformed

    private void itemSistemaSobreSobreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_itemSistemaSobreSobreActionPerformed
    {//GEN-HEADEREND:event_itemSistemaSobreSobreActionPerformed
		this.janelaSobre = new Sobre();
		this.janelaSobre.setVisible(true);
    }//GEN-LAST:event_itemSistemaSobreSobreActionPerformed

    private void itemSistemaSobreAparenciaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_itemSistemaSobreAparenciaActionPerformed
    {//GEN-HEADEREND:event_itemSistemaSobreAparenciaActionPerformed
		lookandfeel.LookAndFeelWindow lookAndFeelWindow = new LookAndFeelWindow();
		lookAndFeelWindow.setVisible(true);
    }//GEN-LAST:event_itemSistemaSobreAparenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemMovientacaoVendas;
    private javax.swing.JButton Logoff;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoAgenda;
    private javax.swing.JButton botaoClientes;
    private javax.swing.JButton botaoMalaDireta;
    private javax.swing.JButton botaoProdutos;
    private javax.swing.JButton botaoServicos;
    private javax.swing.JButton botaoVendas;
    private javax.swing.JMenuItem itemCadastroContatoClientes;
    private javax.swing.JMenuItem itemCadastroContatoFornecedores;
    private javax.swing.JMenuItem itemCadastroEquipamentoEquipamentos;
    private javax.swing.JMenuItem itemCadastroEquipamentoMarca;
    private javax.swing.JMenuItem itemCadastroEquipamentoTipo;
    private javax.swing.JMenuItem itemCadastroEventosLocais;
    private javax.swing.JMenuItem itemCadastroEventosTipos;
    private javax.swing.JMenuItem itemCadastroProdutosCategoria;
    private javax.swing.JMenuItem itemCadastroProdutosProdutos;
    private javax.swing.JMenuItem itemCadastroServicosCategoria;
    private javax.swing.JMenuItem itemCadastroServicosServicos;
    private javax.swing.JMenuItem itemContatosAgenda;
    private javax.swing.JMenuItem itemContatosMalaDireta;
    private javax.swing.JMenuItem itemRelatoriosClientes;
    private javax.swing.JMenuItem itemRelatoriosContasReceber;
    private javax.swing.JMenuItem itemRelatoriosEquipamentos;
    private javax.swing.JMenuItem itemRelatoriosFornecedores;
    private javax.swing.JMenuItem itemRelatoriosVendas;
    private javax.swing.JMenuItem itemSistemaBackupCriar;
    private javax.swing.JMenuItem itemSistemaBackupRestaurar;
    private javax.swing.JMenuItem itemSistemaLogoff;
    private javax.swing.JMenuItem itemSistemaProprietario;
    private javax.swing.JMenuItem itemSistemaSobreAparencia;
    private javax.swing.JMenuItem itemSistemaSobreLicenca;
    private javax.swing.JMenuItem itemSistemaSobreSobre;
    private javax.swing.JMenuItem itemSistemaUsuarioCadastrar;
    private javax.swing.JMenuItem itemSistemaUsuarioSenha;
    private javax.swing.JMenuItem itemUtilitariosCalculadora;
    private javax.swing.JMenuItem itemUtilitariosRecibos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JLabel labelLogotipo;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuCadastroEquipamentos;
    private javax.swing.JMenu menuCadastroEventos;
    private javax.swing.JMenu menuCadastroProdutos;
    private javax.swing.JMenu menuCadastroServicos;
    private javax.swing.JMenu menuCadastrosContatos;
    private javax.swing.JMenu menuContatos;
    private javax.swing.JMenu menuMovimentacao;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuRelatoriosContas;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenu menuSistemaBackup;
    private javax.swing.JMenu menuSistemaSobre;
    private javax.swing.JMenu menuSistemaUsuario;
    private javax.swing.JMenu menuUtilitarios;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelLogotipo;
    private javax.swing.JPopupMenu.Separator separadorCadastroEquipamentos;
    private javax.swing.JPopupMenu.Separator separadorCadastroProdutos;
    private javax.swing.JPopupMenu.Separator separadorCadastroServicos;
    // End of variables declaration//GEN-END:variables
    //JANELAS
    private CadastroMarcasEquipamentos	janelaCadastroMarcasEquipamentos;
    private CadastroTipoEquipamentos	janelaCadastroTipoEquipamentos;
    private CadastroEquipamentos		janelaCadastroEquipamentos;
    private CadastroCategoriaProduto	janelaCadastroCategoriaProduto;
    private CadastroProdutos			janelaCadastroProdutos;
    private CadastroCategoriaServico	janelaCadastroCategoriaServico;
    private CadastroServicos			janelaCadastroServicos;
    private CadastroTipoEvento			janelaCadastroTipoEvento;
    private CadastroLocaisEventos		janelaCadastroLocaisEventos;
    private CadastroClientes			janelaCadastroClientes;
    private CadastroFornecedores		janelaCadastroFornecedores;
    private Agenda						janelaAgenda;
    private MalaDireta					janelaMalaDireta;
    private Vendas						janelaVendas;
    private RelatorioClientes			janelaRelatorioClientes;
    private RelatorioFornecedores		janelaRelatorioFornecedores;
    private RelatorioEquipamento		janelaRelatorioEquipamento;
    private RelatorioVendas				janelaRelatorioVendas;
    private Recibos						janelaRecibos;
    private DadosEmpresa				janelaDadosProprietario;
    private CadastroUsuario				janelaCadastroUsuario;
    private AlteraSenha					janelaAlteraSenha;
	private Backup						janelaBackup;
	private RestaurarBackup				janelaRestaurarBackup;
	private Licenca						janelaLicensa;
	private Sobre						janelaSobre;
    
    //JANELAS ERROS
    private ErroAbrirCalculadora		janelaErroAbrirCalculadora;
	private ErroEmpresaNaoCadastrada	janelaEmpresaNaoCadastrada;
	
	//Controladores
	private ControladorEmpresa			controlEmpresa;
	
	private estudiofotografico.EstudioFotografico estudio;
}
