/*
 * EstudioFotografico 1.0 - Gerenciador de Estudio Fotografico
 * Copyright (C) 2014 Rogério Eduardo Pereira
 * 
 * This file is part of EstudioFotografico 1.0.
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU 
 * General Public License as published by the Free Software Foundation, either version 3 of the 
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 */

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package estudiofotografico.view.janelas;

import estudiofotografico.control.ControladorClientes;
import estudiofotografico.control.ControladorEventos;
import estudiofotografico.control.ControladorVendas;
import estudiofotografico.model.Clientes;
import estudiofotografico.model.LocaisEventos;
import estudiofotografico.model.TiposEventos;
import estudiofotografico.model.Vendas;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rogério Eduardo Pereira
 * Data Criação: Mar 27, 2014
 */
public class ProcuraVendas extends javax.swing.JFrame implements KeyListener, ContainerListener
{

    /** Creates new form ProcuraVendas */
    public ProcuraVendas() {
        initComponents();

        //Adiciona Listeners de Botões
        addKeyAndContainerListenerRecursively(this);
		
		this.setLocationRelativeTo(null);
		
		this.configuraTabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        textoCliente = new javax.swing.JTextField();
        labelTipoEvento = new javax.swing.JLabel();
        textoTipoEvento = new javax.swing.JTextField();
        labelLocalEvento = new javax.swing.JLabel();
        textoLocalEvento = new javax.swing.JTextField();
        botaoPesquisarLocalEvento = new javax.swing.JButton();
        botaoPesquisarTipoEvento = new javax.swing.JButton();
        botaoPesquisarCliente = new javax.swing.JButton();
        textoData = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        botaoPesquisar = new javax.swing.JButton();
        botaoSelecionar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procura Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(95, 133, 169), null), "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Codigo");

        jLabel5.setText("Data");

        labelCliente.setText("Cliente");

        textoCliente.setEditable(false);

        labelTipoEvento.setText("Tipo Evento");

        textoTipoEvento.setEditable(false);

        labelLocalEvento.setText("Local Evento");

        textoLocalEvento.setEditable(false);

        botaoPesquisarLocalEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/map_magnify.png"))); // NOI18N
        botaoPesquisarLocalEvento.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoPesquisarLocalEventoActionPerformed(evt);
            }
        });

        botaoPesquisarTipoEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/cake_magnify.png"))); // NOI18N
        botaoPesquisarTipoEvento.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoPesquisarTipoEventoActionPerformed(evt);
            }
        });

        botaoPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/procurarCliente.png"))); // NOI18N
        botaoPesquisarCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoPesquisarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoEvento)
                    .addComponent(labelLocalEvento)
                    .addComponent(labelCliente)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoTipoEvento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoCliente)
                            .addComponent(textoLocalEvento, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoPesquisarCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botaoPesquisarTipoEvento)
                                .addComponent(botaoPesquisarLocalEvento))))
                    .addComponent(textoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoPesquisarCliente)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCliente)
                                        .addComponent(textoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelTipoEvento)
                                    .addComponent(textoTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(botaoPesquisarTipoEvento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLocalEvento)
                            .addComponent(textoLocalEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botaoPesquisarLocalEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(95, 133, 169), null), "Controle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        botaoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/magnifier.png"))); // NOI18N
        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoPesquisarActionPerformed(evt);
            }
        });

        botaoSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/accept.png"))); // NOI18N
        botaoSelecionar.setText("Selecionar");
        botaoSelecionar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoSelecionarActionPerformed(evt);
            }
        });

        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/delete.png"))); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/cancel.png"))); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
            .addComponent(botaoLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(botaoPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Codigo", "Cliente", "Tipo Evento", "Data", "Hora", "Local Evento"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabelaVendas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tabelaVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPesquisarLocalEventoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoPesquisarLocalEventoActionPerformed
    {//GEN-HEADEREND:event_botaoPesquisarLocalEventoActionPerformed
        this.janelaProcuraLocaisEvento = new ProcuraLocaisEvento(this, true);
        this.janelaProcuraLocaisEvento.setVisible(true);
    }//GEN-LAST:event_botaoPesquisarLocalEventoActionPerformed

    private void botaoPesquisarTipoEventoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoPesquisarTipoEventoActionPerformed
    {//GEN-HEADEREND:event_botaoPesquisarTipoEventoActionPerformed
        this.janelaProcuraTiposEvento = new ProcuraTiposEvento(this, true);
        this.janelaProcuraTiposEvento.setVisible(true);
    }//GEN-LAST:event_botaoPesquisarTipoEventoActionPerformed

    private void botaoPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoPesquisarClienteActionPerformed
    {//GEN-HEADEREND:event_botaoPesquisarClienteActionPerformed
        this.janelaProcuraClientes = new ProcuraClientes(this, true);
        this.janelaProcuraClientes.setVisible(true);
    }//GEN-LAST:event_botaoPesquisarClienteActionPerformed

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoPesquisarActionPerformed
    {//GEN-HEADEREND:event_botaoPesquisarActionPerformed
        this.apagaTabela();

        control = new ControladorVendas();
        List<Vendas> lista = control.getVendasBusca	(
														this.getCodigo(),
														this.getCliente(),
														this.getTipoEvento(),
														this.getLocalEvento(),
														this.getData()
													);
        this.insereDados(lista);
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void botaoSelecionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoSelecionarActionPerformed
    {//GEN-HEADEREND:event_botaoSelecionarActionPerformed
        if(tabelaVendas.getSelectedRow() != -1)
        {
            if(janelaVendas != null)
            {
                janelaVendas.codigo = Long.parseLong(tabelaVendas.getValueAt(tabelaVendas.getSelectedRow(), 0).toString());
				janelaVendas.limpaTela();
				janelaVendas.getVendaByCodigo();
            }

            this.dispose();
        }
    }//GEN-LAST:event_botaoSelecionarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoLimparActionPerformed
    {//GEN-HEADEREND:event_botaoLimparActionPerformed
        this.textoCodigo.setText("");
        this.textoCliente.setText("");
        this.textoLocalEvento.setText("");
        this.textoTipoEvento.setText("");
        this.textoData.setCalendar(null);
        this.apagaTabela();
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoCancelarActionPerformed
    {//GEN-HEADEREND:event_botaoCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

	/*
	 * Método setTamanhoTabela
	 * Define o tamanho das colunas da tabela
	 */
	private void configuraTabela()
	{
		DefaultTableCellRenderer alinhamento = new DefaultTableCellRenderer();
		alinhamento.setHorizontalAlignment(SwingConstants.LEFT);
		tabelaVendas.getColumnModel().getColumn(0).setCellRenderer(alinhamento);
		
		tabelaVendas.getColumnModel().getColumn(0).setPreferredWidth(70); 
		tabelaVendas.getColumnModel().getColumn(1).setPreferredWidth(150); 
		tabelaVendas.getColumnModel().getColumn(2).setPreferredWidth(100); 
		tabelaVendas.getColumnModel().getColumn(3).setPreferredWidth(72); 
		tabelaVendas.getColumnModel().getColumn(4).setPreferredWidth(58);
		tabelaVendas.getColumnModel().getColumn(5).setPreferredWidth(150); 
	}
    /*
	 * Método apagaTabela
	 * Apaga a tabela
	 */
	public void apagaTabela()
	{
		DefaultTableModel modelo = (DefaultTableModel) tabelaVendas.getModel();
		while(tabelaVendas.getRowCount() > 0)
			modelo.removeRow(0);
	}
	
	/*
	 * Método insereDados
	 * insere os dados da busca na tabela
	 */
	public void insereDados(List<Vendas> lista)
	{
		DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
		
		for(Vendas venda: lista)
		{
			
			DefaultTableModel modelo = (DefaultTableModel) this.tabelaVendas.getModel();
			modelo.addRow(new String[]	{
											venda.getCodigo().toString(),
											venda.getCliente().getNome(),
											venda.getTipoEvento().getTipo(),
											df.format(venda.getDia().getTime()),
											venda.getHora(),
											venda.getLocalEvento().getNome()
										});
		}
	}
	
	/*
	 * Método setClienteByCod
	 * Busca o Cliente pelo codigo
	 */
	public void setClienteByCod (Long codigo)
	{
		this.controlClientes	= new ControladorClientes();
		Clientes cliente		= this.controlClientes.getClientesByCodigo(codigo);
		this.textoCliente.setText(cliente.getCodigo()+" - "+cliente.getNome());
		this.controlClientes = null;
	}
	
	/*
	 * Método setTipoByCod
	 * Busca o Local do Evento pelo codigo
	 */
	public void setTipoByCod (Long codigo)
	{
		this.controlEventos	= new ControladorEventos();
		TiposEventos tipos	= this.controlEventos.getTiposEventosByCod(codigo);
		this.textoTipoEvento.setText(tipos.getCodigo()+" - "+tipos.getTipo());
		this.controlClientes = null;
	}
	
	/*
	 * Método setLocalByCod
	 * Busca o Local do Evento pelo codigo
	 */
	public void setLocalByCod (Long codigo)
	{
		this.controlEventos	= new ControladorEventos();
		LocaisEventos local	= this.controlEventos.getLocalByCodigo(codigo);
		this.textoLocalEvento.setText(local.getCodigo()+" - "+local.getNome());
		this.controlClientes = null;
	}

    /*
     * Métodos da Classe
     */
    
    //METODOS KEYLISTENER
    //KEYLISTENER RECURSIVO (COLOCA EM TODOS OS COMPONENTES)
    private void addKeyAndContainerListenerRecursively(Component c) 
    {  
        try 
        {  
            c.addKeyListener(this);  
            if (c instanceof Container) 
            {  
                Container cont = (Container) c;  
                cont.addContainerListener(this);  
                Component[] children = cont.getComponents();  
                for (int i = 0; i < children.length; i++) 
                {  
                    addKeyAndContainerListenerRecursively(children[i]);  
                }  
            }  
        } catch (Exception e) {  
            //Anuncie Aqui  
        }  
    }  

    //EVENTOS KEYLISTENER
    public void keyTyped(KeyEvent e) {}  
    public void keyReleased(KeyEvent e) {}  
    public void componentAdded(ContainerEvent e) {}  
    public void componentRemoved(ContainerEvent e) {}  
    public void keyPressed(KeyEvent e) 
    {
        //TECLA ENTER
        if(e.getKeyCode() == KeyEvent.VK_ENTER)
        {

        }

        //TECLA ESC
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            this.Fechar();
        }
    }
    
    
    /*
     * Método Fechar()
     * Fecha Janela
     */
    private void Fechar()
    {
        this.dispose();
    }
	
	private Long getCodigo ()
    {
        if(this.textoCodigo.getText().isEmpty())
			return null;
		else
			return Long.parseLong(this.textoCodigo.getText());
    }
	
	private Long getCliente()
	{
        if(this.textoCliente.getText().isEmpty())
			return null;
		else
		{
			String cliente[] = textoCliente.getText().split(" - ");
			return Long.parseLong(cliente[0]);
		}
    }
	
	private Long getTipoEvento()
	{
        if(this.textoTipoEvento.getText().isEmpty())
			return null;
		else
		{
			String cliente[] = textoTipoEvento.getText().split(" - ");
			return Long.parseLong(cliente[0]);
		}
    }
	
	private Long getLocalEvento()
	{
        if(this.textoLocalEvento.getText().isEmpty())
			return null;
		else
		{
			String cliente[] = textoLocalEvento.getText().split(" - ");
			return Long.parseLong(cliente[0]);
		}
    }
	
	private Calendar getData()
	{
		return this.textoData.getCalendar();
	}


	public void setJanelaVendas (estudiofotografico.view.janelas.Vendas janelaVendas)
	{
		this.janelaVendas = janelaVendas;
	}

	
	
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcuraVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcuraVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcuraVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcuraVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcuraVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoPesquisarCliente;
    private javax.swing.JButton botaoPesquisarLocalEvento;
    private javax.swing.JButton botaoPesquisarTipoEvento;
    private javax.swing.JButton botaoSelecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelLocalEvento;
    private javax.swing.JLabel labelTipoEvento;
    private javax.swing.JTable tabelaVendas;
    private javax.swing.JTextField textoCliente;
    private javax.swing.JTextField textoCodigo;
    private com.toedter.calendar.JDateChooser textoData;
    private javax.swing.JTextField textoLocalEvento;
    private javax.swing.JTextField textoTipoEvento;
    // End of variables declaration//GEN-END:variables
	private ControladorVendas						control;
	private ControladorClientes						controlClientes;
	private ControladorEventos						controlEventos;
	
	private CadastroServicos						janeCadastroServicos;
	private estudiofotografico.view.janelas.Vendas	janelaVendas;
	private ProcuraClientes							janelaProcuraClientes;
	private ProcuraLocaisEvento						janelaProcuraLocaisEvento;
	private ProcuraTiposEvento						janelaProcuraTiposEvento;
}
