/*
 * EstudioFotografico 1.0 - Gerenciador de Estudio Fotografico
 * Copyright (C) 2014 Rogério Eduardo Pereira
 * 
 * This file is part of EstudioFotografico 1.0.
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU 
 * General Public License as published by the Free Software Foundation, either version 3 of the 
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package estudiofotografico.view.janelas;

import estudiofotografico.control.ControladorClientes;
import estudiofotografico.control.ControladorEmpresa;
import estudiofotografico.control.ControladorRelatorios;
import estudiofotografico.control.util.Extenso;
import estudiofotografico.model.Clientes;
import estudiofotografico.model.Empresa;
import java.awt.Component;
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;

/**
 *
 * @author farofa
 */
public class Recibos extends javax.swing.JFrame implements KeyListener, ContainerListener{

    /**
     * Creates new form cadastroMarcas
     */
    public Recibos() {
        initComponents();
        addKeyAndContainerListenerRecursively(this);
        this.setLocationRelativeTo(null);
		this.setEmpresa();
		this.setData();
    }
    
    //BOTAO ESC E ENTER
    //LISTENERS DO FRAME
    //KEYLISTENER RECURSIVO (COLOCA EM TODOS OS COMPONENTES)
    private void addKeyAndContainerListenerRecursively(Component c) 
    {  
        try 
        {  
            c.addKeyListener(this);  
            if (c instanceof Container) 
            {  
                Container cont = (Container) c;  
                cont.addContainerListener(this);  
                Component[] children = cont.getComponents();  
                for (int i = 0; i < children.length; i++) 
                {  
                    addKeyAndContainerListenerRecursively(children[i]);  
                }  
            }  
        } catch (Exception e) {  
            //Anuncie Aqui  
        }  
    }  
    
    //EVENTOS KEYLISTENER
    public void keyTyped(KeyEvent e) {}  
    public void keyReleased(KeyEvent e) {}  
    public void componentAdded(ContainerEvent e) {}  
    public void componentRemoved(ContainerEvent e) {}  
    public void keyPressed(KeyEvent e) 
    {
        //TECLA ENTER
        if(e.getKeyCode() == KeyEvent.VK_ENTER)
        {
            
        }
        
        //TECLA ESC
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            dispose();
        }
    }

	/*
	 * Método getEmpresa
	 * Obtem os dados da empresa
	 */
	private void setEmpresa()
	{
		this.controlEmpresa = new ControladorEmpresa();
		this.empresa		= this.controlEmpresa.getEmpresa();
		this.textoMunicipio.setText(this.empresa.getCidade());
		this.textoNomeAssinatura.setText(this.empresa.getNome());
		this.controlEmpresa = null;
	}
	
	/*
	 * Método setData
	 * Define a data atual do sistema
	 */
	private void setData()
	{
		this.textoData.setCalendar(new GregorianCalendar());
	}
	
	/*
	 * Método setClienteByCod
	 * Seta o cliente pelo Codigo
	 */
	public void setClienteByCod(Long codigo)
	{
		this.controlCliente	= new ControladorClientes();
		this.cliente			= this.controlCliente.getClientesByCodigo(codigo);
		this.textoCliente.setText(this.cliente.getNome());
		this.controlCliente = null;
	}
	
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        labelRecebemos = new javax.swing.JLabel();
        textoCliente = new javax.swing.JTextField();
        botaoPesquisarCliente = new javax.swing.JButton();
        labelImportancia = new javax.swing.JLabel();
        labelReferente = new javax.swing.JLabel();
        painelReferente = new javax.swing.JScrollPane();
        textoReferente = new javax.swing.JTextArea();
        labelObservacao = new javax.swing.JLabel();
        painelObs = new javax.swing.JScrollPane();
        textoObs = new javax.swing.JTextArea();
        labelMunicipio = new javax.swing.JLabel();
        textoMunicipio = new javax.swing.JTextField();
        labelData = new javax.swing.JLabel();
        textoData = new com.toedter.calendar.JDateChooser();
        labelNomeAssinatura = new javax.swing.JLabel();
        textoNomeAssinatura = new javax.swing.JTextField();
        labelComplemento = new javax.swing.JLabel();
        textoComplemento = new javax.swing.JTextField();
        textoValor = new formattedFields.jTextMoeda();
        botaoGerarRecibo = new javax.swing.JButton();
        botaoLimparRecibo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerador de Recibo");
        setBounds(new java.awt.Rectangle(250, 230, 0, 0));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/estudiofotografico/view/img/camera-photo-5.png")));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(95, 133, 169), null), "Dados do Recibo"));

        labelRecebemos.setText("Recebemos de:");

        textoCliente.setEditable(false);
        textoCliente.setFocusable(false);

        botaoPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/procurarCliente.png"))); // NOI18N
        botaoPesquisarCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoPesquisarClienteActionPerformed(evt);
            }
        });

        labelImportancia.setText("A Importância de: ");

        labelReferente.setText("Referente à:");

        textoReferente.setColumns(20);
        textoReferente.setLineWrap(true);
        textoReferente.setWrapStyleWord(true);
        painelReferente.setViewportView(textoReferente);

        labelObservacao.setText("Observações:");

        textoObs.setColumns(20);
        textoObs.setLineWrap(true);
        textoObs.setWrapStyleWord(true);
        painelObs.setViewportView(textoObs);

        labelMunicipio.setText("Municipio");

        textoMunicipio.setEditable(false);
        textoMunicipio.setFocusable(false);

        labelData.setText("Data");

        textoData.setFocusable(false);

        labelNomeAssinatura.setText("Nome (Assinatura)");

        textoNomeAssinatura.setEditable(false);
        textoNomeAssinatura.setFocusable(false);

        labelComplemento.setText("Complemento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeAssinatura)
                    .addComponent(labelMunicipio)
                    .addComponent(labelData)
                    .addComponent(labelComplemento)
                    .addComponent(labelImportancia)
                    .addComponent(labelRecebemos)
                    .addComponent(labelReferente)
                    .addComponent(labelObservacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelReferente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoData, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoMunicipio)
                            .addComponent(textoNomeAssinatura)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoPesquisarCliente))
                            .addComponent(painelObs))
                        .addComponent(textoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textoComplemento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecebemos)
                    .addComponent(textoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelImportancia)
                    .addComponent(textoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelReferente)
                    .addComponent(painelReferente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelObs, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelObservacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMunicipio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNomeAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomeAssinatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComplemento)
                    .addComponent(textoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoGerarRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/money_add.png"))); // NOI18N
        botaoGerarRecibo.setText("Gerar Recibo");
        botaoGerarRecibo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoGerarReciboActionPerformed(evt);
            }
        });

        botaoLimparRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estudiofotografico/view/img/money_delete.png"))); // NOI18N
        botaoLimparRecibo.setText("Limpar Recibo");
        botaoLimparRecibo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoLimparReciboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoGerarRecibo)
                .addGap(18, 18, 18)
                .addComponent(botaoLimparRecibo)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoGerarRecibo)
                    .addComponent(botaoLimparRecibo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoGerarReciboActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoGerarReciboActionPerformed
    {//GEN-HEADEREND:event_botaoGerarReciboActionPerformed
		SimpleDateFormat	fmtData			= new SimpleDateFormat("dd/MM/yyyy");
							this.extenso	= new Extenso(this.textoValor.getValue());
		String[]			data			= fmtData.format(this.textoData.getDate()).split("/");
		
		if(data[1].equals("01"))
			data[1] = "Janeiro";
		else if(data[1].equals("02"))
			data[1] = "Fevereiro";
		else if(data[1].equals("03"))
			data[1] = "Março";
		else if(data[1].equals("04"))
			data[1] = "Abril";
		else if(data[1].equals("05"))
			data[1] = "Maio";
		else if(data[1].equals("06"))
			data[1] = "Junho";
		else if(data[1].equals("07"))
			data[1] = "Julho";
		else if(data[1].equals("08"))
			data[1] = "Agosto";
		else if(data[1].equals("09"))
			data[1] = "Setembro";
		else if(data[1].equals("10"))
			data[1] = "Outubro";
		else if(data[1].equals("11"))
			data[1] = "Novembro";
		else if(data[1].equals("12"))
			data[1] = "Dezembro";
		
		ControladorRelatorios relatorio	= new ControladorRelatorios();
		relatorio.parametros.put("de", textoCliente.getText().toUpperCase());
		relatorio.parametros.put("importanciaValor", textoValor.getText());
		relatorio.parametros.put("importanciaExtenso", this.extenso.toString().toUpperCase());
		relatorio.parametros.put("referente", textoReferente.getText().toUpperCase());
		relatorio.parametros.put("observacoes", textoObs.getText().toUpperCase());
		relatorio.parametros.put("municipio", textoMunicipio.getText().toUpperCase());
		relatorio.parametros.put("data", data[0]+" de "+data[1]+" de "+data[2]);
		relatorio.parametros.put("assinatura", textoNomeAssinatura.getText());
		relatorio.parametros.put("complemento", textoComplemento.getText().toUpperCase());
		
		relatorio.GeraRelatório("relatorios/Recibo.jasper");
    }//GEN-LAST:event_botaoGerarReciboActionPerformed

    private void botaoLimparReciboActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoLimparReciboActionPerformed
    {//GEN-HEADEREND:event_botaoLimparReciboActionPerformed
		textoCliente.setText("");
		textoValor.setText("");
		textoReferente.setText("");
		textoObs.setText("");
		this.setData();
		textoObs.setText("");
    }//GEN-LAST:event_botaoLimparReciboActionPerformed

    private void botaoPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoPesquisarClienteActionPerformed
    {//GEN-HEADEREND:event_botaoPesquisarClienteActionPerformed
		this.janelaProcuraClientes = new ProcuraClientes(this, true);
		this.janelaProcuraClientes.setVisible(true);
    }//GEN-LAST:event_botaoPesquisarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Recibos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGerarRecibo;
    private javax.swing.JButton botaoLimparRecibo;
    private javax.swing.JButton botaoPesquisarCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelComplemento;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelImportancia;
    private javax.swing.JLabel labelMunicipio;
    private javax.swing.JLabel labelNomeAssinatura;
    private javax.swing.JLabel labelObservacao;
    private javax.swing.JLabel labelRecebemos;
    private javax.swing.JLabel labelReferente;
    private javax.swing.JScrollPane painelObs;
    private javax.swing.JScrollPane painelReferente;
    private javax.swing.JTextField textoCliente;
    private javax.swing.JTextField textoComplemento;
    private com.toedter.calendar.JDateChooser textoData;
    private javax.swing.JTextField textoMunicipio;
    private javax.swing.JTextField textoNomeAssinatura;
    private javax.swing.JTextArea textoObs;
    private javax.swing.JTextArea textoReferente;
    private formattedFields.jTextMoeda textoValor;
    // End of variables declaration//GEN-END:variables
	private Extenso				extenso;
	private Clientes			cliente;
	private Empresa				empresa;
	private ControladorEmpresa	controlEmpresa;
	private ControladorClientes	controlCliente;
	private ProcuraClientes		janelaProcuraClientes;
}
